### ISSUE TITLE
Error trying to double open socket

### ISSUE THREAD

**Issue by bcoopers** [bzier/gym-mupen64plus#58]
When trying to run the Simple Test program described in `README.md`, I encountered an error.

It seems that a socket with the controller server is opened twice without being closed, giving the error:
```
socket.error: [Errno 98] Address already in use
```

This happens inside the first call to `env.render()`

```
[2018-05-18 18:38:04,113] Making new env: Mario-Kart-Luigi-Raceway-v0
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    env.render()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/core.py", line 174, in render
    return self._render(mode=mode, close=close)
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/core.py", line 341, in _render
    return self.env.render(mode, close)
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/core.py", line 174, in render
    return self._render(mode=mode, close=close)
  File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 175, in _render
    from gym.envs.classic_control import rendering
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 100, in <module>
    from pyglet.gl.lib import GLException
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/lib.py", line 143, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/lib_glx.py", line 43, in <module>
    import pyglet.lib
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/lib.py", line 61, in <module>
    script_path = pyglet.resource.get_script_home()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/resource.py", line 88, in <module>
    standard_library.install_aliases()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "/home/bcoopers/Code/gym-mupen64plus/test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 47, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 73, in __init__
    self.controller_server, self.controller_server_thread = self._start_controller_server()
  File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 189, in _start_controller_server
    frame_skip      = config['FRAME_SKIP']) # TODO: Environment argument (with issue #26)
  File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 379, in __init__
    super(ControllerHTTPServer, self).__init__(server_address, self.ControllerRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by bcoopers** [comment]
I resolved the error by making _CONTROLLER_SERVER, _CONTROLLER_SERVER_THREAD module level variable of mupen64plus_env.py instead of class member variables of Mupen64PlusEnv, and closing them by registering _stop_controller_server to atexit, though this seems like kind of a hacky solution to me.

**Comment by bzier** [comment]
Thanks @bcoopers. Yes, I've seen this error quite a bit. It often occurs after running the code once, and trying to run again. The controller server is not being properly closed. Usually I just bail out of the Python process and start a new one. I actually have a fix for this that is less hacky (I think, based on your description and my memory from a couple weeks ago). I'll try to get that merged in this weekend (probably tomorrow).

**Comment by bzier** [comment]
I was looking for my code/branch for this and having a hard time finding it, but realized that I had just documented the fix [here](https://github.com/bzier/gym-mupen64plus/issues/4#issuecomment-386831670).  I just pushed a commit with the fix applied.

**Comment by bcoopers** [comment]
Hmm this doesn't seem to have solved the issue. I am still getting the same error as above.

The problem seems to happen at the line:

`from gym.envs.classic_control import rendering`

in Mupen64PlusEnv._render. From my interpretation of the stack trace, it looks like it's somehow re-calling my test code:

File "/home/bcoopers/Code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 175, in _render
    from gym.envs.classic_control import rendering
  File "/home/bcoopers/.local/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 100, in <module>
    from pyglet.gl.lib import GLException
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/lib.py", line 143, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/gl/lib_glx.py", line 43, in <module>
    import pyglet.lib
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/lib.py", line 61, in <module>
    script_path = pyglet.resource.get_script_home()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/home/bcoopers/.local/lib/python2.7/site-packages/pyglet/resource.py", line 88, in <module>
    standard_library.install_aliases()
  File "/home/bcoopers/.local/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "/home/bcoopers/Code/gym-mupen64plus/test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')

I have no idea how this is possible... trying to figure out a workaround

**Comment by bcoopers** [comment]
The workaround was easy. I just needed to wrap my test script in

if __name__ == "__main__":
    main()

and that fixed the issue.

Still not sure how my test code was getting double imported... But let me submit a PR to change the documentation to include this.

**Comment by bzier** [comment]
@bcoopers Was your file named `test.py`? This came up [a while ago](https://github.com/bzier/gym-mupen64plus/issues/31#issuecomment-347974880)... another thing to add to the `README`. Seems like you may have found a different solution to the same problem. Basically, it gets caught in a recursive loop, continuing to find `test.py` in the current directory and running multiple times. In this case, the first call opens the socket, and the second call fails because the socket is already in use. Naming the file anything else should do the trick... or your solution of actually defining a method. I'll take a close look at the PR in a few and likely merge that in.

**Comment by bzier** [comment]
@bcoopers 
Thanks for the PR; the change looks good. I successfully tested the script and merged it in. Please let me know if you continue to encounter the issue.
